-- ASLAN production migration
-- This migration is additive and matches the existing production schema.
-- It does not recreate or destroy existing products/courses/orders tables.

create schema if not exists private;

alter table public.products add column if not exists features jsonb not null default '{}'::jsonb;

create table if not exists public.work_gallery (
  id uuid primary key default gen_random_uuid(),
  image_url text not null,
  caption text,
  created_at timestamptz not null default now()
);

create table if not exists public.social_links (
  id bigint generated by default as identity primary key,
  platform text not null unique,
  url text not null,
  created_at timestamptz not null default now()
);

alter table public.leads add column if not exists product_id bigint;

create or replace function private.is_admin()
returns boolean
language sql
stable
security definer
set search_path = auth, public, pg_temp
as $$
  select coalesce(
    (select raw_app_meta_data ->> 'role' from auth.users where id = (select auth.uid())),
    ''
  ) = 'admin';
$$;

revoke all on function private.is_admin() from public;
grant execute on function private.is_admin() to authenticated;

alter table public.products enable row level security;
alter table public.work_gallery enable row level security;
alter table public.social_links enable row level security;
alter table public.leads enable row level security;

create policy "products_public_read" on public.products
  for select to anon, authenticated
  using (active = true);
create policy "products_admin_insert" on public.products
  for insert to authenticated
  with check ((select private.is_admin()));
create policy "products_admin_update" on public.products
  for update to authenticated
  using ((select private.is_admin()))
  with check ((select private.is_admin()));
create policy "products_admin_delete" on public.products
  for delete to authenticated
  using ((select private.is_admin()));

create policy "gallery_public_read" on public.work_gallery
  for select to anon, authenticated using (true);
create policy "gallery_admin_insert" on public.work_gallery
  for insert to authenticated with check ((select private.is_admin()));
create policy "gallery_admin_update" on public.work_gallery
  for update to authenticated
  using ((select private.is_admin()))
  with check ((select private.is_admin()));
create policy "gallery_admin_delete" on public.work_gallery
  for delete to authenticated using ((select private.is_admin()));

create policy "social_public_read" on public.social_links
  for select to anon, authenticated using (true);
create policy "social_admin_insert" on public.social_links
  for insert to authenticated with check ((select private.is_admin()));
create policy "social_admin_update" on public.social_links
  for update to authenticated
  using ((select private.is_admin()))
  with check ((select private.is_admin()));
create policy "social_admin_delete" on public.social_links
  for delete to authenticated using ((select private.is_admin()));

create policy "leads_public_insert" on public.leads
  for insert to anon, authenticated
  with check (
    type is not null and length(type) <= 50
  );
create policy "leads_admin_read" on public.leads
  for select to authenticated using ((select private.is_admin()));
create policy "leads_admin_update" on public.leads
  for update to authenticated
  using ((select private.is_admin()))
  with check ((select private.is_admin()));
create policy "leads_admin_delete" on public.leads
  for delete to authenticated using ((select private.is_admin()));

insert into public.social_links (platform, url) values
  ('whatsapp', 'https://wa.me/213558265070'),
  ('facebook', 'https://facebook.com/aslan_modelling'),
  ('instagram', 'https://instagram.com/aslan_modelling'),
  ('tiktok', 'https://tiktok.com/@aslan_modelling')
on conflict (platform) do update set url = excluded.url;
