import Link from 'next/link';
import { site } from '@/lib/config';
import { getProducts } from '@/lib/data';
import { createClient } from '@/lib/supabase/server';

export default async function HomePage() {
  const products = (await getProducts()).slice(0, 3);
  const supabase = await createClient();
  const { data: publicPosts } = await supabase.from('posts').select('id, author_id, title, content, published_at').eq('visibility', 'public').eq('status', 'published').order('published_at', { ascending: false }).limit(6);
  const authorIds = [...new Set((publicPosts ?? []).map(p => p.author_id))];
  const { data: authors } = authorIds.length ? await supabase.from('profiles').select('id, full_name, username, avatar_path').in('id', authorIds) : { data: [] };
  const authorMap = new Map((authors ?? []).map(a => [a.id, a]));
  const communityPosts = [];
  for (const post of publicPosts ?? []) {
    const author = authorMap.get(post.author_id);
    let avatar_url = null;
    if (author?.avatar_path) { const s = await supabase.storage.from('aslan-media').createSignedUrl(author.avatar_path, 3600); avatar_url = s.data?.signedUrl ?? null; }
    const { data: media } = await supabase.from('media_assets').select('id, object_path, media_type').eq('post_id', post.id).limit(4);
    const mediaWithUrls = [];
    for (const item of media ?? []) { const s = await supabase.storage.from('aslan-media').createSignedUrl(item.object_path, 3600); mediaWithUrls.push({ ...item, signed_url: s.data?.signedUrl ?? null }); }
    communityPosts.push({ ...post, author, avatar_url, media: mediaWithUrls });
  }
  return <main>
    <section className="section"><div className="wrap"><span className="kicker">{site.name}</span><h1 className="display">نبني الجودة. <span className="gold">نصنع الثقة.</span></h1><p className="lead">تنجيد • خياطة • تفصيل — منتجات مخصصة، خدمات تنفيذية، وتكوين مهني ضمن منظومة ASLAN.</p><div className="actions"><Link className="button primary" href="/products">استكشف المنتجات</Link><Link className="button secondary" href="/services">اطلب خدمة</Link></div></div></section>
    <section className="section"><div className="wrap"><div className="section-heading row"><div><span className="kicker">COMMUNITY</span><h2>منشورات مجتمع ASLAN</h2><p>المنشورات العامة تظهر هنا مباشرة، مع صورة واسم صاحب المنشور.</p></div><div className="actions"><Link href="/members">الأعضاء ↗</Link><Link href="/account/posts">أنشئ منشورًا ↗</Link></div></div>{communityPosts.length ? <div className="grid three">{communityPosts.map(post => <article className="card" key={post.id} style={{display:'grid',gap:10}}><div style={{display:'flex',alignItems:'center',gap:10}}>{post.avatar_url ? <img src={post.avatar_url} alt="" style={{width:48,height:48,borderRadius:'50%',objectFit:'cover'}}/> : <div style={{width:48,height:48,borderRadius:'50%',display:'grid',placeItems:'center',background:'var(--surface-2,#eee)'}}>👤</div>}<div><strong>{post.author?.full_name || post.author?.username || 'عضو ASLAN'}</strong>{post.author?.username && <div className="muted">@{post.author.username}</div>}</div></div><h3>{post.title}</h3><p>{post.content}</p>{post.media.map(item => item.signed_url && (item.media_type === 'video' ? <video key={item.id} src={item.signed_url} controls style={{width:'100%',borderRadius:12}}/> : <img key={item.id} src={item.signed_url} alt="مرفق المنشور" style={{width:'100%',borderRadius:12}}/>))}{post.author?.username && <Link href={`/members/${encodeURIComponent(post.author.username)}`}>عرض ملف العضو ↗</Link>}</article>)}</div> : <div className="card"><h3>لا توجد منشورات عامة بعد.</h3><p>عندما ينشر عضو منشورًا بظهور «عام» سيظهر هنا.</p><Link href="/members">تصفح الأعضاء ↗</Link></div>}</div></section>
    <section className="section"><div className="wrap"><div className="section-heading"><span className="kicker">ASLAN</span><h2>منظومة تنتج وتخدم وتكوّن وتتوسع</h2><p>نبني العمل حول مهاراتنا ومنتجاتنا وخدماتنا، مع بنية رقمية قابلة للتوسع تدريجيًا.</p></div><div className="grid three"><article className="card"><span className="number">01</span><h3>تنجيد • خياطة • تفصيل</h3><p>منتجات ومنفذات مخصصة تجمع بين الحرفة والتصميم وجودة التنفيذ.</p><Link href="/products">استكشف المنتجات ↗</Link></article><article className="card"><span className="number">02</span><h3>الخدمات التنفيذية</h3><p>خدمات تقنية وتنفيذية مرتبطة بخبرة ASLAN.</p><Link href="/services">استكشف الخدمات ↗</Link></article><article className="card"><span className="number">03</span><h3>الأكاديمية</h3><p>تكوين مهني وتقني قابل للتطبيق والتوسع.</p><Link href="/academy">استكشف الأكاديمية ↗</Link></article></div></div></section>
    <section className="section"><div className="wrap"><div className="section-heading row"><div><span className="kicker">COLLECTION</span><h2>مختارات ASLAN</h2></div><Link href="/products">كل المنتجات ↗</Link></div>{products.length ? <div className="grid three">{products.map((product,index)=><article className="card product-card" key={product.id}><span className="number">{String(index+1).padStart(2,'0')}</span><h3>{product.name || `منتج ASLAN ${index+1}`}</h3>{product.description&&<p>{product.description}</p>}<Link href="/products">عرض المنتج ↗</Link></article>)}</div> : <div className="card"><h3>منتجات ASLAN</h3><p>سيتم عرض المنتجات هنا عند توفر بيانات المنتجات.</p><Link href="/products">الانتقال إلى المنتجات ↗</Link></div>}</div></section>
    <section className="section dark"><div className="wrap"><div className="grid three"><article><span className="kicker">SERVICES</span><h2>خدمات تنفيذية</h2><p>حلول عملية مبنية على الخبرة الفنية والتنفيذ الميداني.</p><Link href="/services">اطلب خدمة ↗</Link></article><article><span className="kicker">ACADEMY</span><h2>تكوين مهني</h2><p>تحويل الخبرة والحرفة إلى برامج تكوين قابلة للتطبيق.</p><Link href="/academy">تعرف على الأكاديمية ↗</Link></article><article><span className="kicker">PARTNERS</span><h2>الشركاء</h2><p>منظومة علاقات وشراكات قابلة للنمو.</p><Link href="/partners">استكشف الشراكات ↗</Link></article></div></div></section>
    <section className="section"><div className="wrap"><div className="cta"><span className="kicker">ASLAN MODELLING GROUP</span><h2>لنبنِ العمل معًا.</h2><p>للاستفسارات، طلب خدمة، أو التواصل مع ASLAN.</p><Link className="button primary" href="/contact">تواصل معنا</Link></div></div></section>
  </main>;
}
