'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import MediaUploader from '@/components/MediaUploader';
import MemberActions from '@/components/MemberActions';

type Media={id:string;media_type:'image'|'video'|'file';signed_url:string|null;object_path?:string};
type Contribution={id:string;user_id:string;type:string;title:string;content:string;visibility:string;status:string;created_at:string;featured?:boolean;media?:Media[];avatar_url?:string|null;authorName?:string|null;username?:string|null};
const labels:Record<string,string>={suggestion:'اقتراح',design:'تصميم',model:'نموذج',post:'مشاركة'};
const statuses:Record<string,string>={pending:'قيد المراجعة',needs_revision:'تحتاج تعديل',accepted:'مقبولة',published:'منشورة',rejected:'مرفوضة'};
export default function ContributionCard({item}:{item:Contribution}){
 const router=useRouter();const [editing,setEditing]=useState(false);const [type,setType]=useState(item.type);const [title,setTitle]=useState(item.title);const [content,setContent]=useState(item.content);const [visibility,setVisibility]=useState(item.visibility);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function save(){setBusy(true);setError('');const r=await fetch('/api/account/contributions',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({contributionId:item.id,type,title,content,visibility})});const d=await r.json().catch(()=>({}));if(!r.ok){setError(d.error||'تعذر تعديل المساهمة.');setBusy(false);return;}setEditing(false);setBusy(false);router.refresh();}
 async function remove(){if(!confirm('حذف هذه المساهمة نهائيًا؟'))return;setBusy(true);const r=await fetch('/api/account/contributions?contributionId='+encodeURIComponent(item.id),{method:'DELETE'});const d=await r.json().catch(()=>({}));if(!r.ok){setError(d.error||'تعذر حذف المساهمة.');setBusy(false);return;}router.refresh();}
 const author={id:item.user_id,full_name:item.authorName,username:item.username,avatar_url:item.avatar_url};
 return <article className='social-post card'><header className='social-post__header'><div className='social-author'><a className='social-author__identity' href={item.username?'/members/'+encodeURIComponent(item.username):'#'}>{item.avatar_url?<img src={item.avatar_url} alt='' className='social-avatar'/>:<div className='social-avatar social-avatar--fallback'>AS</div>}<div><strong className='social-author__name'>{item.authorName||item.username||'عضو ASLAN'}</strong><div className='social-author__meta'><span>@{item.username||'member'}</span><span>· {labels[item.type]||item.type}</span><span>· {statuses[item.status]||item.status}</span><span>· {item.visibility}</span></div></div></a><MemberActions member={author} showProfile={false}/><div className='post-menu-wrap'><button className='icon-button' aria-label='خيارات المساهمة' onClick={()=>setEditing(v=>!v)}>⋮</button></div></header>{item.featured&&<div className='featured-badge'>★ Featured</div>}{editing?<div className='social-edit'><select value={type} onChange={e=>setType(e.target.value)}><option value='suggestion'>اقتراح</option><option value='design'>تصميم</option><option value='model'>نموذج</option><option value='post'>مشاركة</option></select><input value={title} onChange={e=>setTitle(e.target.value)} maxLength={160}/><textarea value={content} onChange={e=>setContent(e.target.value)} maxLength={10000} rows={6}/><select value={visibility} onChange={e=>setVisibility(e.target.value)}><option value='public'>عام</option><option value='friends'>الأصدقاء</option><option value='private'>خاص</option></select><MediaUploader contributionId={item.id}/><div className='actions'><button className='btn primary' onClick={save} disabled={busy}>حفظ</button><button className='btn secondary' onClick={()=>setEditing(false)}>إلغاء</button><button className='btn secondary' onClick={remove} disabled={busy}>حذف</button></div></div>:<><h2 className='social-post__title'>{item.title}</h2><p className='social-post__body'>{item.content}</p>{!!item.media?.length&&<div className='social-media'>{item.media.map(m=>m.signed_url&&(m.media_type==='video'?<video key={m.id} src={m.signed_url} controls className='social-media__item'/>:m.media_type==='image'?<img key={m.id} src={m.signed_url} alt='' className='social-media__item'/>:<a key={m.id} href={m.signed_url} target='_blank' rel='noreferrer' className='social-file'>📎 {m.object_path?.split('/').pop()||'فتح المستند'}</a>))}</div>}</>} {error&&<p className='error-text' role='alert'>{error}</p>}<small className='muted'>{new Date(item.created_at).toLocaleString('ar-DZ')}</small></article>;
}