'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import MediaUploader from '@/components/MediaUploader';

type Props={participant:{id:string;full_name:string|null;username:string|null;avatar_url?:string|null};onClose?:()=>void;embedded?:boolean};
type Message={id:string;conversation_id:string;sender_id:string;body:string;created_at:string;read_at:string|null;media?:Array<{id:string;media_type:'image'|'video'|'file';signed_url:string|null;object_path:string}>};

export default function MessengerPopover({participant,onClose,embedded=false}:Props){
 const [conversationId,setConversationId]=useState('');const [messages,setMessages]=useState<Message[]>([]);const [body,setBody]=useState('');const [error,setError]=useState('');const [sending,setSending]=useState(false);const endRef=useRef<HTMLDivElement|null>(null);
 async function openConversation(){setError('');const r=await fetch('/api/account/conversations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({participantId:participant.id})});const d=await r.json().catch(()=>({}));if(!r.ok){setError(d.error||'لا يمكن بدء المراسلة.');return;}setConversationId(d.conversation.id);await load(d.conversation.id);}
 async function load(id:string){const r=await fetch('/api/account/messages?conversationId='+encodeURIComponent(id),{cache:'no-store'});const d=await r.json().catch(()=>({}));if(r.ok)setMessages(d.messages||[]);else setError(d.error||'تعذر تحميل الرسائل.');}
 useEffect(()=>{openConversation()},[participant.id]);
 useEffect(()=>{endRef.current?.scrollIntoView({behavior:'smooth'})},[messages]);
 async function send(e:React.FormEvent){e.preventDefault();if(!conversationId||(!body.trim()))return;setSending(true);setError('');const r=await fetch('/api/account/messages',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({conversationId,body:body.trim()})});const d=await r.json().catch(()=>({}));if(r.ok){setMessages(items=>[...items,d.message]);setBody('')}else setError(d.error||'تعذر إرسال الرسالة.');setSending(false);}
 const panel=<div className='message-popover__panel'><header className='message-popover__head'>{participant.avatar_url?<img src={participant.avatar_url} alt=''/>:<span className='conversation-avatar'>AS</span>}<div><strong>{participant.full_name||participant.username||'عضو ASLAN'}</strong>{participant.username&&<small>@{participant.username}</small>}</div><div className='message-popover__head-actions'><Link href={'/members/'+encodeURIComponent(participant.username||participant.id)}>الحساب</Link>{onClose&&<button onClick={onClose} aria-label='إغلاق'>×</button>}</div></header>{error?<div className='message-popover__error'>{error}<p className='muted'>قد تكون إعدادات استقبال الرسائل لدى هذا العضو لا تسمح لك بالمراسلة.</p></div>:<><div className='message-popover__body'>{messages.map(m=><div key={m.id} className={'message-row '+(m.sender_id===participant.id?'message-row--in':'message-row--out')}><div className='message-bubble'><div>{m.body}</div>{m.media?.length&&<div className='message-attachments'>{m.media.map(a=>a.signed_url&&(a.media_type==='image'?<img key={a.id} src={a.signed_url} alt=''/>:a.media_type==='video'?<video key={a.id} src={a.signed_url} controls/>:<a key={a.id} href={a.signed_url} target='_blank' rel='noreferrer'>📎 {a.object_path.split('/').pop()}</a>))}</div>}<small>{new Date(m.created_at).toLocaleTimeString('ar-DZ',{hour:'2-digit',minute:'2-digit'})}</small></div></div>)}<div ref={endRef}/></div><div className='message-popover__composer'><form onSubmit={send}><textarea value={body} onChange={e=>setBody(e.target.value)} rows={2} placeholder='اكتب رسالة...' onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();e.currentTarget.form?.requestSubmit()}}}/><button className='btn primary' disabled={sending||!body.trim()}>إرسال</button></form>{conversationId&&<MediaUploader messageId={messages[messages.length-1]?.sender_id?messages[messages.length-1]?.id:undefined} compact/>}</div></>}</div>;
 return embedded?panel:<div className='message-popover' role='dialog'>{panel}</div>;
}